### PR TITLE
Feature multisite

### PR DESCRIPTION
**Pull request by pjohanneson**
Added Multisite capability to the project, including:
* subfolder or subdomain Multisite activation
* network-activated plugins
* network-enabled default theme

### CODE REVIEW

**Comment by flurinduerst** [comment]
Thanks a lot for your contribution! It is highly appreciated. Just as a note: I didn't find the time to check and merge this request as of now. It will be the next thing i'll do here.

**Comment by johnpitchko** [comment]
Any updates on when this will be merged into the master branch?

**Comment by flurinduerst** [comment]
This pull-request got delayed a lot and I'm aware of it, sorry. I highly appreciate the contribution. But I'm not sure if this feature would be used a lot. For us, it's very important to keep WPDistillery as clean and minimal as possible. For this reason I created a survey to receive informations about the need of this feature. Please see **https://github.com/flurinduerst/WPDistillery/issues/59**

I might add this to the next major release, maybe we need to swap multisite relevant files to its own folder for clarity.

**Comment by flurinduerst** [comment]
As stated in https://github.com/flurinduerst/WPDistillery/issues/59 I will not merge this PR as we decided to keep WPDistillery as clean as it is. I will add a note to the readme though and link to the PR. Thanks a lot to @pjohanneson for the contribution. Highly appreciate it! 🎉

**Comment by XedinUnknown** [comment]
So, you added a note to the readme, and a link to this PR. But nothing related to how we could have a multisite installation with WPD :)

**Pull request closed without merging**
